# Generated by Django 3.0.4 on 2020-06-02 05:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(choices=[('Going', 'Going'), ('Based', 'Located'), ('Been', 'Been'), ('Not', 'No plan yet')], default='Not', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('base', 'Based'), ('work', 'For work'), ('visit', 'For visit')], default='base', max_length=5)),
                ('info', models.TextField(max_length=300)),
            ],
        ),
    ]
