# Generated by Django 3.0.4 on 2020-06-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('Going', 'Planning to visit'), ('Based', 'Located now'), ('Been', 'Visited'), ('Not', 'No plan yet')], default='Not', max_length=6),
        ),
        migrations.RemoveField(
            model_name='travel',
            name='name',
        ),
        migrations.AddField(
            model_name='travel',
            name='name',
            field=models.ManyToManyField(to='travel.Place'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.CharField(choices=[('base', 'Based'), ('work', 'For work'), ('visit', 'For visit')], default='base', max_length=6),
        ),
    ]
