# Generated by Django 3.0.4 on 2020-06-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20200602_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(choices=[('Going', 'Planning to visit'), ('Base', 'Located now'), ('Been', 'Visited'), ('Not', 'No plan yet')], default='Not', max_length=6),
        ),
        migrations.RemoveField(
            model_name='travel',
            name='name',
        ),
        migrations.AddField(
            model_name='travel',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
