# Generated by Django 3.0.4 on 2020-06-03 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20200602_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='place',
            new_name='Places',
        ),
        migrations.RenameModel(
            old_name='travel',
            new_name='Travels',
        ),
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='travels',
            options={'verbose_name_plural': 'Places'},
        ),
    ]
