# Generated by Django 3.0.4 on 2020-06-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20200603_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travels',
            options={'verbose_name_plural': 'Travels'},
        ),
    ]
