# Generated by Django 3.0.4 on 2020-06-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20200604_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='contry',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location_name',
        ),
        migrations.RenameField(
            model_name='travel',
            old_name='place',
            new_name='city',
        ),
    ]
