# Generated by Django 3.0.4 on 2020-06-04 21:31

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'locations_base.json'

def load_data(apps, schema_editor):
  Location = apps.get_model('travel', 'Location')
  jsonfile = Path(__file__).parents[2] / DATA_FILENAME

  with open(str(jsonfile)) as datafile:
    objects = json.load(datafile)
    for obj in objects:
      name = obj.get('city', 'no-name')
      country = obj.get('country', 'no-name')
      longitude = obj.get('lng', 0)
      latitude = obj.get('lat', 0)
      position = fromstr(
          f'POINT({longitude} {latitude})', srid=4326
        )
      Location(location_name=name, country=country, position=position).save()


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20200604_2129'),
    ]

    operations = [
      migrations.RunPython(load_data)
    ]
